-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION postgres;

-- DROP SEQUENCE public.avatar_id_seq;

CREATE SEQUENCE public.avatar_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.gruppi_id_seq;

CREATE SEQUENCE public.gruppi_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.partecipante_spesa_id_seq;

CREATE SEQUENCE public.partecipante_spesa_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.saldi_id_seq;

CREATE SEQUENCE public.saldi_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.spesa_id_seq;

CREATE SEQUENCE public.spesa_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.utente_id_seq;

CREATE SEQUENCE public.utente_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.avatar definition

-- Drop table

-- DROP TABLE public.avatar;

CREATE TABLE public.avatar (
	id serial4 NOT NULL,
	immagine_base64 text NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT avatar_pkey PRIMARY KEY (id)
);


-- public.gruppi definition

-- Drop table

-- DROP TABLE public.gruppi;

CREATE TABLE public.gruppi (
	id serial4 NOT NULL,
	nome varchar(100) NOT NULL,
	link_invito text NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT gruppi_link_invito_key UNIQUE (link_invito),
	CONSTRAINT gruppi_pkey PRIMARY KEY (id)
);


-- public.saldi definition

-- Drop table

-- DROP TABLE public.saldi;

CREATE TABLE public.saldi (
	id serial4 NOT NULL,
	id_creditore int4 NOT NULL,
	id_debitore int4 NOT NULL,
	id_gruppo int4 NOT NULL,
	saldo numeric(10, 2) NOT NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT saldi_pkey PRIMARY KEY (id),
	CONSTRAINT saldi_id_gruppo_fkey FOREIGN KEY (id_gruppo) REFERENCES public.gruppi(id) ON DELETE CASCADE
);


-- public.utente definition

-- Drop table

-- DROP TABLE public.utente;

CREATE TABLE public.utente (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cognome varchar(50) NOT NULL,
	created_at timestamp(6) NOT NULL,
	email varchar(100) NOT NULL,
	nome varchar(50) NOT NULL,
	"password" varchar(255) NOT NULL,
	provider varchar(20) NOT NULL,
	id_avatar int8 NULL,
	username varchar(50) NOT NULL,
	CONSTRAINT uk2vq82crxh3p7upassu0k1kmte UNIQUE (username),
	CONSTRAINT ukgxvq4mjswnupehxnp35vawmo2 UNIQUE (email),
	CONSTRAINT utente_pkey PRIMARY KEY (id),
	CONSTRAINT fkpehu743q2d410i463w5eh3b73 FOREIGN KEY (id_avatar) REFERENCES public.avatar(id)
);


-- public.spesa definition

-- Drop table

-- DROP TABLE public.spesa;

CREATE TABLE public.spesa (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	categoria varchar(50) NOT NULL,
	created_at timestamp(6) NOT NULL,
	"data" date NOT NULL,
	importo numeric(10, 2) NOT NULL,
	id_gruppo int8 NOT NULL,
	id_pagante int8 NOT NULL,
	CONSTRAINT spesa_pkey PRIMARY KEY (id),
	CONSTRAINT fk9uesy1h0ujt9g9ll3hpul4aje FOREIGN KEY (id_pagante) REFERENCES public.utente(id)
);


-- public.partecipante_spesa definition

-- Drop table

-- DROP TABLE public.partecipante_spesa;

CREATE TABLE public.partecipante_spesa (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	quota numeric(10, 2) NOT NULL,
	id_partecipante int8 NOT NULL,
	id_spesa int8 NOT NULL,
	CONSTRAINT partecipante_spesa_pkey PRIMARY KEY (id),
	CONSTRAINT fkg6ic17j7gfb3flfbky7dnrvg9 FOREIGN KEY (id_partecipante) REFERENCES public.utente(id),
	CONSTRAINT fkgqb35yf1flea4q2711uvh7nbw FOREIGN KEY (id_spesa) REFERENCES public.spesa(id)
);



-- DROP FUNCTION public.aggiorna_saldi();

CREATE OR REPLACE FUNCTION public.aggiorna_saldi()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE Saldi
    SET saldo = saldo + NEW.importo / (SELECT COUNT(*) FROM Partecipanti_Spese WHERE id_spesa = NEW.id)
    WHERE id_creditore = NEW.id_pagante AND id_gruppo = NEW.id_gruppo;
    RETURN NEW;
END;
$function$
;

-- DROP FUNCTION public.registra_modifica();

CREATE OR REPLACE FUNCTION public.registra_modifica()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO Log_Modifiche (tabella, operazione, id_record, dettagli)
        VALUES (TG_TABLE_NAME, TG_OP, OLD.id, row_to_json(OLD));
    ELSE
        INSERT INTO Log_Modifiche (tabella, operazione, id_record, dettagli)
        VALUES (TG_TABLE_NAME, TG_OP, NEW.id, row_to_json(NEW));
    END IF;
    RETURN NULL;
END;
$function$
;
